"""initial schema

Revision ID: b0e79c0d6be6
Revises: 
Create Date: 2026-07-16 13:41:02.695865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0e79c0d6be6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journeys',
    sa.Column('journey_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('first_ts', sa.DateTime(), nullable=True),
    sa.Column('last_ts', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('cart_header_id', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('journey_id')
    )
    op.create_index(op.f('ix_journeys_cart_header_id'), 'journeys', ['cart_header_id'], unique=False)
    op.create_index(op.f('ix_journeys_event_id'), 'journeys', ['event_id'], unique=False)
    op.create_index(op.f('ix_journeys_order_id'), 'journeys', ['order_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('emitted_at', sa.DateTime(), nullable=False),
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('logger', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('cart_header_id', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('journey_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.journey_id'], ),
    sa.PrimaryKeyConstraint('alert_id'),
    sa.UniqueConstraint('log_id')
    )
    op.create_index(op.f('ix_alerts_cart_header_id'), 'alerts', ['cart_header_id'], unique=False)
    op.create_index(op.f('ix_alerts_event_id'), 'alerts', ['event_id'], unique=False)
    op.create_index(op.f('ix_alerts_journey_id'), 'alerts', ['journey_id'], unique=False)
    op.create_index(op.f('ix_alerts_order_id'), 'alerts', ['order_id'], unique=False)
    op.create_table('journey_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journey_id', sa.String(), nullable=False),
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.journey_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id', name='uq_journey_events_log_id')
    )
    op.create_index(op.f('ix_journey_events_journey_id'), 'journey_events', ['journey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journey_events_journey_id'), table_name='journey_events')
    op.drop_table('journey_events')
    op.drop_index(op.f('ix_alerts_order_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_journey_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_event_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_cart_header_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_journeys_order_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_event_id'), table_name='journeys')
    op.drop_index(op.f('ix_journeys_cart_header_id'), table_name='journeys')
    op.drop_table('journeys')
    # ### end Alembic commands ###
